name: Build Prism Theme and Snippets

on:
  push:
    branches: [ "development" ]
  pull_request:
    branches: [ "development" ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
    - uses: actions/checkout@v3
    - uses: pnpm/action-setup@v2
      with:
        version: 7
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'pnpm'
    - name: Install dependencies
      run: pnpm install
    - run: pnpm run buildTheme --if-present
    - run: pnpm run buildSnipMHS --if-present
    - name: Pushing the Built Files
      uses: stefanzweifel/git-auto-commit-action@v4
      with:
          commit_message: Automated Build of Theme and Snippet files
          branch: development
